### ISSUE TITLE
INIT_CWD not always accurate in CLI

### ISSUE THREAD

**Issue by ri0t** [capacitor-community/electron#76]
**Describe the bug**
Adding the platform results in a strange file-not-found error, although the file exists.

**To Reproduce**

0. Use rather recent Ionic templated app which generates web and apk builds nicely
1. Run `npx cap add @capacitor-community/electron`
2. Get error about missing configuration

**Expected behavior**
It should add the capacitor-community electron platform

**Screenshots**

```
➜ npx cap add @capacitor-community/electron

> @capacitor-community/electron@1.3.2 capacitor:add
> node dist/cap-scripts.js add

⠋ Adding Electron platformError: capacitor.config.json does not exist, did you setup capacitor in your project root?
✖ Adding Electron platform: capacitor.config.json does not exist, did you setup capacitor in your project root?
(node:4565) UnhandledPromiseRejectionWarning: Error: capacitor.config.json does not exist, did you setup capacitor in your project root?
    at Object.n [as doAdd] (/home/riot/src/isomer/isomer_modules/leerstandsmelder/leerstandsmelder-2/frontend/leerstandsmelder-ionic-ng-autoentities/node_modules/@capacitor-community/electron/dist/cap-scripts.js:6:1016)
    at /home/riot/src/isomer/isomer_modules/leerstandsmelder/leerstandsmelder-2/frontend/leerstandsmelder-ionic-ng-autoentities/node_modules/@capacitor-community/electron/dist/cap-scripts.js:12:363
    at Object.g [as runTask] (/home/riot/src/isomer/isomer_modules/leerstandsmelder/leerstandsmelder-2/frontend/leerstandsmelder-ionic-ng-autoentities/node_modules/@capacitor-community/electron/dist/cap-scripts.js:2:1902)
    at i (/home/riot/src/isomer/isomer_modules/leerstandsmelder/leerstandsmelder-2/frontend/leerstandsmelder-ionic-ng-autoentities/node_modules/@capacitor-community/electron/dist/cap-scripts.js:12:311)
    at /home/riot/src/isomer/isomer_modules/leerstandsmelder/leerstandsmelder-2/frontend/leerstandsmelder-ionic-ng-autoentities/node_modules/@capacitor-community/electron/dist/cap-scripts.js:12:718
    at Object.parcelRequire.Focm../common (/home/riot/src/isomer/isomer_modules/leerstandsmelder/leerstandsmelder-2/frontend/leerstandsmelder-ionic-ng-autoentities/node_modules/@capacitor-community/electron/dist/cap-scripts.js:12:915)
    at f (/home/riot/src/isomer/isomer_modules/leerstandsmelder/leerstandsmelder-2/frontend/leerstandsmelder-ionic-ng-autoentities/node_modules/@capacitor-community/electron/dist/cap-scripts.js:1:468)
    at parcelRequire.FoEN (/home/riot/src/isomer/isomer_modules/leerstandsmelder/leerstandsmelder-2/frontend/leerstandsmelder-ionic-ng-autoentities/node_modules/@capacitor-community/electron/dist/cap-scripts.js:1:771)
    at Object.<anonymous> (/home/riot/src/isomer/isomer_modules/leerstandsmelder/leerstandsmelder-2/frontend/leerstandsmelder-ionic-ng-autoentities/node_modules/@capacitor-community/electron/dist/cap-scripts.js:1:1023)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
(node:4565) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4565) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Desktop (please complete the following information):**

- OS: Debian Sid
- Version:
  - npm: 7.3.0
  - ionic: 6.12.3
 
**Additional context**
The capacitor configuration exists and has been used to add android and ios platforms already:
```
➜ cat capacitor.config.json 
{
  "appId": "de.foobar.app",
  "appName": "foobar",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "www",
  "plugins": {
    "SplashScreen": {
      "launchShowDuration": 0
    }
  },
  "cordova": {}
}
```

**Comment by IT-MikeS** [comment]
Do you have an example repo where this is happening, I cant make it happen on my machines.

**Comment by IT-MikeS** [comment]
In the mean time, maybe have a peak at this comment, it sounds like a similar scenario as your issue.

https://github.com/capacitor-community/electron/issues/73#issuecomment-759653910

**Comment by cmlad** [comment]
Facing exactly the same issue and the linked comment didn't help.

The code [1] makes the search go 3 levels up, and so for me it's looking for the config file in my home dir.

I am brand new to Node, but the workaround I found was to just set `INIT_CWD` to a dir 3 levels deep, in this case the electron dir that was already created:

```
export INIT_CWD=/home/XXX/src/YYY/node_modules/@capacitor-community/electron
npx cap add @capacitor-community/electron
```

Running from within a child dir didn't work.

To repro on a brand new system:

```
# Install NVM
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash

# Install latest Node (v15.5.1) and npm (0.37.2)
nvm install node

# Install Ionic (6.12.3)
npm install -g @ionic/cli

# Create an app
ionic start ZZZ sidemenu --type=react --capacitor

# Build (after CD-ing into the dir). I also tried ionic build, same result
npm run build

# Try to add electron and get same error as OP
npx cap add @capacitor-community/electron
```

One guess could be that my capacitor version is 2.4.6, but the docs seem to require 2.3.0 (`Note: these instructions require a Capacitor version of ^2.3.0`)

[1] https://github.com/capacitor-community/electron/blob/main/cap-scripts/common.ts#L49

**Comment by ri0t** [comment]
> Facing exactly the same issue and the linked comment didn't help.
> 
> The code [1] makes the search go 3 levels up, and so for me it's looking for the config file in my home dir.
> 
> I am brand new to Node, but the workaround I found was to just set `INIT_CWD` to a dir 3 levels deep, in this case the electron dir that was already created:

That is exactly what helped, here. I now have it added, by employing the workaround. Thank you!

**Comment by ri0t** [comment]
@IT-MikeS my repository - which this happened with, if you still want to try it out: https://github.com/Leerstandsmelder/leerstandsmelder-zwo-frontend

**Comment by mfrieling** [comment]
> > Facing exactly the same issue and the linked comment didn't help.
> > The code [1] makes the search go 3 levels up, and so for me it's looking for the config file in my home dir.
> > I am brand new to Node, but the workaround I found was to just set `INIT_CWD` to a dir 3 levels deep, in this case the electron dir that was already created:
> 
> That is exactly what helped, here. I now have it added, by employing the workaround. Thank you!

This helped for me as well, but then `npx cap open @capacitor-community/electron` failed with

```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "
> photo-gallery@1.0.0 electron:start
> npm run build && electron ./


> photo-gallery@1.0.0 build
> tsc

The futex facility returned an unexpected error code.
```

The corresponding log file:
```
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'run',
0 verbose cli   'capacitor:open'
0 verbose cli ]
1 info using npm@7.4.0
2 info using node@v15.6.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/dev/projects/photo-gallery/node_modules/@capacitor-community/electron/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/home/dev/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 verbose npm-session 8c15630092c3dd0f
20 timing npm:load Completed in 20ms
21 timing command:run-script Completed in 136966ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:379:20)
22 verbose stack     at maybeClose (node:internal/child_process:1065:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:296:5)
23 verbose pkgid @capacitor-community/electron@1.3.2
24 verbose cwd /home/dev/projects/photo-gallery/node_modules/@capacitor-community/electron
25 verbose Linux 5.4.72-microsoft-standard-WSL2
26 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "capacitor:open"
27 verbose node v15.6.0
28 verbose npm  v7.4.0
29 error code 1
30 error path /home/dev/projects/photo-gallery/node_modules/@capacitor-community/electron
31 error command failed
32 error command sh -c node dist/cap-scripts.js open
33 verbose exit 1
```
I'm using Capacitor CLI 2.4.6 as well. Don't know if those errors are related or not.

**Comment by jordytenden** [comment]
Was making a NuxtJS - Capacitor prototype when running into same issue, had added android to Capacitor before, cd'ing into the Android folder and rerunning `npx cap add @capacitor-community/electron` did the trick for me. But I also now have trouble opening the platform using `npx cap open electron` command.

**Comment by arthurrmp** [comment]
Been having this error here on macOS trying to run `npx cap add @capacitor-community/electron` from Visual Studio Code. Running from a iTerm2 tab on the same folder worked fine. Not sure why, but maybe it can help someone.

**Comment by Loller79** [comment]
> Facing exactly the same issue and the linked comment didn't help.
> 
> The code [1] makes the search go 3 levels up, and so for me it's looking for the config file in my home dir.
> 
> I am brand new to Node, but the workaround I found was to just set `INIT_CWD` to a dir 3 levels deep, in this case the electron dir that was already created:
> 
> ```
> export INIT_CWD=/home/XXX/src/YYY/node_modules/@capacitor-community/electron
> npx cap add @capacitor-community/electron
> ```
> 
> Running from within a child dir didn't work.
> 
> To repro on a brand new system:
> 
> ```
> # Install NVM
> curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
> 
> # Install latest Node (v15.5.1) and npm (0.37.2)
> nvm install node
> 
> # Install Ionic (6.12.3)
> npm install -g @ionic/cli
> 
> # Create an app
> ionic start ZZZ sidemenu --type=react --capacitor
> 
> # Build (after CD-ing into the dir). I also tried ionic build, same result
> npm run build
> 
> # Try to add electron and get same error as OP
> npx cap add @capacitor-community/electron
> ```
> 
> One guess could be that my capacitor version is 2.4.6, but the docs seem to require 2.3.0 (`Note: these instructions require a Capacitor version of ^2.3.0`)
> 
> [1] https://github.com/capacitor-community/electron/blob/main/cap-scripts/common.ts#L49

Same issue here, the INIT_CWD trick here did work flawlessly, I can't share my project source to help you debug but I can tell you that this happens on an Archlinux + Gnome distro too.

**Comment by bnsouza** [comment]
> Facing exactly the same issue and the linked comment didn't help.
> 
> The code [1] makes the search go 3 levels up, and so for me it's looking for the config file in my home dir.
> 
> [1] https://github.com/capacitor-community/electron/blob/main/cap-scripts/common.ts#L49

I have installed today the plugin and have the same error: `capacitor.config.json does not exist`. 

- OS: macOs Catalina 10.15.7.
- npm: 7.3.0
- node: v15.14.0

I saw this issue and this comment and tried to declare the INIT_CWD env but the error still there. So I debugged the code and saw the INIT_CWD was returning the **_webapp folder_** and not the `node_modules/@capacitor-community/electron` folder.

So I replaced 
`function i(){const r=process.env.INIT_CWD;return e.join(r,"../","../","../")}`

for
`function i(){const r=process.env.INIT_CWD;return e.join(r,"/")}`

on `node_modules/@capacitor-community/electron/dist/cap-scripts.js` and it worked...

I don't know if this is because of node/npm version or because of macOs... So I have changed the `common.ts` and made a PR...

I hope this can help others!

**Comment by IT-MikeS** [comment]
This is resolved in v3 so I will close this for now

**Comment by Ekagra** [comment]
I followed the answer and did `set INIT_CWD=C:\Users\My-Name\blah\node_modules\@capacitor-community\electron`
but still this error persists:

```
Error: capacitor.config.json does not exist, did you setup capacitor in your project root?
    at Object.n [as doAdd] (C:\Users\My-Name\blah\node_modules\@capacitor-community\electron\dist\cap-scripts.js:6:1016)
    at C:\Users\My-Name\blah\node_modules\@capacitor-community\electron\dist\cap-scripts.js:12:363
    at Object.g [as runTask] (C:\Users\My-Name\blah\node_modules\@capacitor-community\electron\dist\cap-scripts.js:2:1888)
    at i (C:\Users\My-Name\blah\node_modules\@capacitor-community\electron\dist\cap-scripts.js:12:311)
    at C:\Users\My-Name\blah\node_modules\@capacitor-community\electron\dist\cap-scripts.js:12:718
    at Object.parcelRequire.Focm../common (C:\Users\My-Name\blah\node_modules\@capacitor-community\electron\dist\cap-scripts.js:12:915)
    at f (C:\Users\My-Name\blah\node_modules\@capacitor-community\electron\dist\cap-scripts.js:1:468)
    at parcelRequire.FoEN (C:\Users\My-Name\blah\node_modules\@capacitor-community\electron\dist\cap-scripts.js:1:771)
    at Object.<anonymous> (C:\Users\My-Name\blah\node_modules\@capacitor-community\electron\dist\cap-scripts.js:1:1023)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
```
