### ISSUE TITLE
Electron 11 only shows Web Content after resize, minimize or drag Main Window

### ISSUE THREAD

**Issue by hatsantos** [capacitor-community/electron#80]
**Describe the bug**
I'm building an app with Electron, Capacitor, Ionic and Angular.

My app runs smooth without any problems if I use electron version 10.2.0, but if I upgrade to Electron 11.2.0 my app starts with an empty white screen. The strange thing is, if I inspect the page the HTML is there but the window shows only white (black if dark mode). My apps starts displaying if I do one of the following:

- Resize the app window
- Move the window;
- Minimize or maximize the window;
- Run for example a registered shortcut command (CTRL + H for a MessageBox with App help screen);

It looks like the main windows looses focus or stops to render, but then when I click, min/max the windows or drag it gain focus and continuous to render... I already tried to force focus without success.

`MainWindow.focus();`

Any hint on what may be causing this?

**To Reproduce**
Update to Electron from 10.2.0 or 10.3.0 to 11.2.0.

**Expected behavior**
App should run without the need to resize, move or minimize/maximize the window.

**Screenshots**
App shows nothing until something is done with the window (drag, min/max, loose focus, etc).
![image](https://user-images.githubusercontent.com/36542752/104818633-b68fb080-5820-11eb-920e-4214f4b94963.png)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser Electron 11.2.0
- Capacitor 2.4.6
- Capacitor Electron 1.3.2

**Additional context**
If I try to force MainWindow.show(); in my main.ts after the app inits it shows and render the web page, but it breaks the splashcreen, showing an white area (same as the window size) around the splashscreen image...

![image](https://user-images.githubusercontent.com/36542752/104818753-78df5780-5821-11eb-80cb-1cbf896beca4.png)

**Comment by hatsantos** [comment]
Just tested with a basic project.

- Created a new Ionic Angular App using: ionic start
- Added Capacitor support: npm install @capacitor/core @capacitor/cli
- Init Capacitor: npx cap init
- Build Ionic App: ionic build --prod
- Installed @capacitor-community/electron dependencie: npm i @capacitor-community/electron
- Add the electron platform: npx cap add @capacitor-community/electron
- Run the electron platform: npx cap open @capacitor-community/electron

![image](https://user-images.githubusercontent.com/36542752/104821204-28242a80-5832-11eb-938c-f07348586317.png)

An then, if I move the window, the web app renders...

![image](https://user-images.githubusercontent.com/36542752/104821237-64578b00-5832-11eb-8b40-c73204e348b8.png)

**Comment by IT-MikeS** [comment]
Very odd, I'll have a look into this

**Comment by hatsantos** [comment]
Hello @IT-MikeS !

I have been hammering my head around this all day, without any success...

If you use the sample project provided in the previous comment, or simply setup a new project using Ionic and Capacitor, I think you will be able to reproduce the issue.

Let me know if I can help with anything.

**Comment by IT-MikeS** [comment]
While I haven't yet figured out why on Electron v11+ it happens. I have found that if you disable the splashscreen in the config the display issue no longer occurs (maybe....., tried it 25 times with no issue but cant guarantee).

**Comment by LuizTokuhara** [comment]
I have the same issue... disabled the splashscreen but no results, need to drag the window around to show the content.
By the way, it only happens on windows.

**Comment by eduboxgithub** [comment]
I upgraded my app to the new Angular version 11.1.0. The problem still exists with this new version of Angular, probably it's not related to Angular, just to let you know...

I tested another theory, related to the splash screen... At the end of the "ready" event, I called the unmaximize() method:

```
app.on("ready", async () => 
{
                MainApp.init();

		MainWindow = MainApp.getMainWindow();    

                //.... other initialization stuff

               MainWindow.unmaximize();
}
```

The apps start and the webapp is rendered without the need to drag the main window, but the splashscreen, instead of appear on a "transparent" window, shows up in a white window with the same size as the application (not the splashscreen size).

I also tested your suggestion @IT-MikeS . I can confirm that in my case it worked... Disabling the splash screen did the trick. The app starts and renders the webapp, but I would prefer to not loose the splash screen feature :(

```
public GetMainWindowConfig():CapacitorElectronConfig
{
        const configElectron: CapacitorElectronConfig = 
        {
            mainWindow: 
            {
                windowOptions: 
                {
                    width: 1280,
                    height: 720,
                    show: true,
                    webPreferences: 
                    {
                        nodeIntegration: true
                    }
                }
            },
            splashScreen: 
            {
                **useSplashScreen: false,**
            }
        };

        return configElectron;
}
```

**Comment by hatsantos** [comment]
I upgraded my app to the new Angular version 11.1.0. The problem still exists with this new version of Angular, probably it's not related to Angular, just to let you know...

I tested another theory, related to the splash screen... At the end of the "ready" event, I called the unmaximize() method:

```
app.on("ready", async () => 
{
                MainApp.init();

		MainWindow = MainApp.getMainWindow();    

                //.... other initialization stuff

               MainWindow.unmaximize();
}
```

The apps start and the webapp is rendered without the need to drag the main window, but the splashscreen, instead of appear on a "transparent" window, shows up in a white window with the same size as the application (not the splashscreen size).

I also tested your suggestion @IT-MikeS . I can confirm that in my case it worked... Disabling the splash screen did the trick. The app starts and renders the webapp, but I would prefer to not loose the splash screen feature :(

```
public GetMainWindowConfig():CapacitorElectronConfig
{
        const configElectron: CapacitorElectronConfig = 
        {
            mainWindow: 
            {
                windowOptions: 
                {
                    width: 1280,
                    height: 720,
                    show: true,
                    webPreferences: 
                    {
                        nodeIntegration: true
                    }
                }
            },
            splashScreen: 
            {
                **useSplashScreen: false,**
            }
        };

        return configElectron;
}
```

**Comment by IT-MikeS** [comment]
Note, this seems to be an issue directly with electron > 10.3.0. More info at the issue referenced below.

https://github.com/electron/electron/issues/27353

**Comment by eduboxgithub** [comment]
Hello, @IT-MikeS.

Thank you for your finding that issue.

I was already looking at the capacitor electron source code to see the logic behind the show/hide of the splash/main window:

![image](https://user-images.githubusercontent.com/13800439/105416507-28596700-5c32-11eb-950b-c1a4adce2f0f.png)

In the issue you mentioned they suggest a "solution" that looks and smells kinda "hacky", but it works...
Don't know if is the best or the right moment to do it, but looking at the capacitor electron code I also added a "dom-ready" event and after some delay called the show() of the main window.

```
app.on("ready", async () => 
{
		MainApp.init();

		MainWindow = MainApp.getMainWindow();

		MainWindow.webContents.on("dom-ready", () => 
		{
			MainWindow.hide();

			setTimeout(() => 
			{
				MainWindow.show();
			}, 100);
		});
});
```
This seems to fix the initial behavior.

In the meantime, I also tested my app against electron 12.0.0-beta.16 version. 
With the latest beta version of version 12, the app work, there's no white screen and no need to drag the window to render the web app.

Unfortunately, my app is not totally compatible with electron 12 (some deprecated API) and I can't go any further than version 11.

**Comment by hatsantos** [comment]
Hello, @IT-MikeS.

Thank you for your finding that issue.

I was already looking at the capacitor electron source code to see the logic behind the show/hide of the splash/main window:

![image](https://user-images.githubusercontent.com/36542752/105417587-be41c180-5c33-11eb-9a5e-27af2672bc9b.png)

In the issue you mentioned they suggest a "solution" that looks and smells kinda "hacky", but it works...
Don't know if is the best or the right moment to do it, but looking at the capacitor electron code I also added a "dom-ready" event and after some delay called the show() of the main window.

```
app.on("ready", async () => 
{
		MainApp.init();

		MainWindow = MainApp.getMainWindow();

		MainWindow.webContents.on("dom-ready", () => 
		{
			MainWindow.hide();

			setTimeout(() => 
			{
				MainWindow.show();
			}, 100);
		});
});
```
This seems to fix the initial behavior.

In the meantime, I also tested my app against electron 12.0.0-beta.16 version. 
With the latest beta version of version 12, the app work, there's no white screen and no need to drag the window to render the web app.

Unfortunately, my app is not totally compatible with electron 12 (some deprecated API) and I can't go any further than version 11.

**Comment by IT-MikeS** [comment]
I pushed out a platform update (v1.3.3) that reverts back to electron ~10.3.1 so new users wont have a ton of frustrations. I will keep this issue open until the issue is resolved. 

If you need electron versions >10, then you can freely update it manually in your project.

Open a terminal in the electron folder of your project and just use `npm i electron@^XX.XX.XX` with your required version. Sam goes for needing to downgrade for any reason too.

**Comment by IT-MikeS** [comment]
Please note this is now fixed in version 1.4.0 (https://github.com/capacitor-community/electron/releases/tag/v1.4.0) of the platform as it now uses v12 of electron. If you need <12 please use >10.4.0 & <11.0.0

**Comment by JuliusSkrisa** [comment]
I am somehow still seeing this issue on 4.1.0 version. with Electron 14. 
when I set `hideMainWindowOnLaunch ` to true, its even worse and no window will show up after splash screen is hidden.

 for now settings the timeout for `this.MainWindow.show()` will solve this.
